"""'2nd'

Revision ID: 5781556f41d7
Revises: eecdf238c1d8
Create Date: 2023-03-01 15:32:59.762655

"""
import sqlalchemy as sa

from alembic import op

# The second migration. Have dropped the column 'round_num' from Accounts table (unused).

# revision identifiers, used by Alembic.
revision = "5781556f41d7"
down_revision = "eecdf238c1d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "round_num")
    op.create_unique_constraint(None, "games", ["chat_id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "games", type_="unique")
    op.add_column(
        "accounts",
        sa.Column("round_num", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
