"""'unique_removed'

Revision ID: decd02f1d9d5
Revises: 5781556f41d7
Create Date: 2023-03-05 17:33:04.308844

"""
import sqlalchemy as sa

from alembic import op

# The third migration. Have removed unique constraints in columns (username, profile_photo_id) of User table

# revision identifiers, used by Alembic.
revision = "decd02f1d9d5"
down_revision = "5781556f41d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_profile_photo_id_key", "users", type_="unique")
    op.drop_constraint("users_username_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.create_unique_constraint("users_profile_photo_id_key", "users", ["profile_photo_id"])
    # ### end Alembic commands ###
