"""'admin_added'

Revision ID: e8f3bcb7f4d0
Revises: 362f72e21d70
Create Date: 2023-03-09 13:20:30.263436

"""
import sqlalchemy as sa

from alembic import op

# Have added 'admins' table.

# revision identifiers, used by Alembic.
revision = "e8f3bcb7f4d0"
down_revision = "362f72e21d70"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admins")
    # ### end Alembic commands ###
