"""'initial'

Revision ID: eecdf238c1d8
Revises: 
Create Date: 2023-02-28 15:15:13.216059

"""
import sqlalchemy as sa

from alembic import op

# The first migration. Tables creation (according to Models).

# revision identifiers, used by Alembic.
revision = "eecdf238c1d8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("chat_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("bot_state", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
        sa.UniqueConstraint("chat_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("profile_photo_id", sa.String(), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("total_games", sa.Integer(), nullable=False),
        sa.Column("efficiency", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("profile_photo_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("game_id", sa.BIGINT(), nullable=False),
        sa.Column("vote", sa.Boolean(), nullable=False),
        sa.Column("scores", sa.Integer(), nullable=False),
        sa.Column("photo_num", sa.String(), nullable=False),
        sa.Column("round_num", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "game_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("games")
    # ### end Alembic commands ###
